language: java
sudo: false
dist: trusty
services:
  - postgresql
before_script:
  - psql -c 'create database hello;' -U postgres
  - psql -c 'create user bot with password \'qwe321\';' -U postgres
  - psql -c 'grant all privileges on database hello to bot;' -U postgres
  - cat sql/create.sql | psql -U postgres hello
