language: java
sudo: false
dist: trusty
services:
  - postgresql
before_script:
  - psql -c 'create database hello;' -U postgres
  - mv src/main/resources/database.properties.travis src/main/resources/database.properties
  - cat sql/create.sql | psql -U postgres hello
